site_name: pywintray
site_url: !ENV [SITE_URL, 'http://localhost:8000']
theme: 
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}

plugins:
  - search:
  - macros:
      module_name: ./macros
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
      - locale: zh
        name: 中文
        default: true
      - locale: en
        name: English

