
def quit()->None:...
def mainloop()->None:...

class TrayIcon:
    def __init__(self, tip:str ="pywintray", hidden=False)->None:...
    def show(self)->None:...
    def hide(self)->None:...

    @property
    def tip(self)->str:...
    @tip.setter
    def tip(self, value:str)->None:...

    @property
    def hidden(self)->str:...
