import typing

def quit()->None:...
def mainloop()->None:...

class TrayIcon:
    def __init__(
        self,
        icon_path: str|None = None,
        icon_handle: int|None = None,
        tip:str ="pywintray", 
        hidden:bool=False,
        load_icon_large: bool = False,
        load_icon_index: bool = False,
    )->None:...
    def show(self)->None:...
    def hide(self)->None:...

    @property
    def tip(self)->str:...
    @tip.setter
    def tip(self, value:str)->None:...

    @property
    def hidden(self)->str:...
