import typing

class IconHandle:
    @classmethod
    def from_int(cls, value:int)->IconHandle:...
    @property
    def value(self)->int:...

def load_icon(path:str, large=True, index=0) -> IconHandle:...

def quit()->None:...
def mainloop()->None:...

class TrayIcon:
    def __init__(
        self,
        icon: IconHandle,
        tip:str ="pywintray", 
        hidden:bool=False
    )->None:...
    def show(self)->None:...
    def hide(self)->None:...

    @property
    def tip(self)->str:...
    @tip.setter
    def tip(self, value:str)->None:...

    @property
    def hidden(self)->str:...
