name: Build Wheel and Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build (Python ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [windows-latest, windows-11-arm]

        include:
        - os: windows-11-arm
          skip_tests: true

        exclude:
        # python 3.10 doesn't support windows on arm
        - python-version: "3.10"
          os: windows-11-arm

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }} (${{ matrix.os }})
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build wheel
      shell: cmd
      run: |
        pip wheel . -w wheelhouse

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v4
      with:
        name: wheel-${{ matrix.python-version }}-${{ matrix.os }}
        path: wheelhouse/*.whl

    - name: Run tests
      if: ${{ !matrix.skip_tests }}
      shell: cmd
      run: |
        pip install -r requirements-dev.txt
        pip install -f wheelhouse pywintray
        python -m pytest
